<div class="espacos" id="espaco-clube-impacto">

</div>

<!-- divisor divisor clube -->
<section id="divisor-clube" class="d-flex"> 
    <div class="container align-self-center">
        <div class="row">
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
            <div class="col-md-6 align-self-center text-center">
                <h2>Clube de Impacto</h2>
                <p>Café de verdade direto do produtor para a sua casa!</p>
            </div>
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
        </div>
    </div>
</section>
<!-- end of divisor clube -->

<!-- section Nosso Clube Impacto -->
<section id="clube-impacto" class="fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <img id="img1" class="img-fluid no-gutter" src="assets/box.png" alt="">
            </div>
            <div class="col-md-6 justify-content-center text-center">
                <h2 id="h2-price">R$<h1 id="h1-price">25</h1>+ frete*</h2>
                <h5>Escolha como você quer o seu café especial.</h5>
                <div id="choice" class="row align-self-center">
                    <div class="col-md-3 offset-md-3">
                        <form action="/assinar" method="post">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="radio" id="moido" value="moido">
                            <label class="form-check-label" for="moido">Moído</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="radio" id="graos" value="graos">
                            <label class="form-check-label" for="graos">Grãos</label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <button type="submit" target="_blank" id="botao-clube" class="btn btn-lg btn-outline-light">Assinar</button>
                    </div>
                    </form>
                </div>                     
                <p>Mandamos para sua casa 1 pacotinho de café de 250g dentro de uma caixinha maneira!</p>
                <p>Será sempre 1 pacotinho de café especial, moído ou em grãos, de fazendas incríveis que produzem cafés de alta qualidade.</p>
                <p>Hoje mais de 85% dos pequenos produtores não conseguem atingir a pontuação necessária para cafés especiais. Ao assinar o nosso clube ou comprar os cafés de impacto, você ajuda o pequeno produtor a investir no seu negócio e produzir cafés cada vez melhores.</p>
                <p>Está em dúvida? Você pode experimentar antes de assinar comprando uma caixinha avulsa por <span>R$29,00 + Frete*.</span></p>
                <a href="/checkout" target="_blank" id="botao-clube-c" class="btn btn-lg btn-outline-light">Comprar</a> 
                <!-- <a href="https://pag.ae/7WrEXJBG7" target="_blank" id="botao-clube-c" class="btn btn-lg btn-outline-light">Comprar</a>  --> 
                <p><span>*O valor do frete será adicionado no checkout do Pagseguro.</span></p>
            </div>
        </div>
    </div>
</section>
<!-- end of section Nosso Clube Impacto -->

<!-- divisor divisor clube -->
<section id="divisor-clube" class="d-flex"> 
    <div class="container align-self-center">
        <div class="row">
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
            <div class="col-md-6 align-self-center text-center">
                <h2>Edição do mês</h2>
                <p>Todo mês enviaremos 1 pacotinho de 250g pra você.</p>
            </div>
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
        </div>
    </div>
</section>
<!-- end of divisor clube -->

<!-- section Nosso Clube Impacto -->
<section id="clube-impacto" class="fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 text-center">
                <h5>Café especial</h5>
                <p>Hoje, Gilmar e mais 3 irmãos trabalham em suas lavouras no Sítio Boa Vista, cada um cuidando de uma parte dessa terra que já está na terceira geração de uma família de cafeicultores. Gilmar procura mater a cultura de sempre trabalharem juntos e preservarem o meio ambiente e passar para suas 2 filhas, que já expressam o desejo de continuar trabalhando com café e garantir a sucessão familiar nesta atividade. <a href="" id="qr">Confere aqui!</a></p>
                <div class="row">
                    <div class="col-md-12 text-center car-cafe-top">
                        <span id="car-cafe">Altitude</span> 
                        <h6>1200m</h6>
                        <span id="car-cafe">Variedade</span>
                        <h6>Catuaí vermelho IAC-44</h6>
                        <span id="car-cafe">Processo</span>
                        <h6>Natural</h6>
                        <span id="car-cafe">Secagem</span>
                        <h6>Terreiro de concreto</h6>
                        <span id="car-cafe">Notas</span>
                        <h6>Chocolate amargo e Nozes</h6>
                    </div>
                </div>
            </div>
            <div class="col-md-6" id="img-car-cafe">
                <img id="img2" class="img-fluid no-gutters" src="assets/detalhe_indaia.jpeg" alt="">
            </div>
        </div>
    </div>
</section>
<!-- end of section Nosso Clube Impacto -->

<!-- Certifications -->
    <section id="certifications">
        <div class="container">
            <div class="row">
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/LogoMataMinas.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/utz.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/cafesbrasil.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/logo_header_pt.png" alt="">
                </div>
            </div>
        </div>
    </section>
<!-- end of Certifications -->
