<div class="espacos" id="espaco-clube-impacto">

</div>

<!-- divisor divisor clube -->
<section id="divisor-clube" class="d-flex"> 
    <div class="container align-self-center">
        <div class="row">
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
            <div class="col-md-6 align-self-center text-center">
                <h2>Clube de Impacto</h2>
                <p>Café de verdade direto do produtor para a sua casa!</p>
            </div>
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
        </div>
    </div>
</section>
<!-- end of divisor clube -->

<!-- section Nosso Clube Impacto -->
<section id="clube-impacto" class="fluid">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <div class="card shadow mb-4">
                    <img src="assets/box.png" class="card-img-top" alt="">
                    <div class="card-body">
                        <h2 class="card-title mt-4" id="h2-price">R$<h1 id="h1-price">25</h1>por mês + frete*</h2>
                        <h5 class="card-title">Assinatura</h5>
                        <p class="card-text p-3">Faça parte do nosso clube. Enviamos todo mês para sua casa, cafés especiais de produtores incríveis dentro de uma caixinha maneira!</p>
                        <h6 class="card-title w-70 mb-3">Escolha como você vai querer seu café especial</h6>
                        <form id="assinar" action="" method="post">
                            <!-- <input type="hidden" name="idCompra" value="2"> -->
                            <input type="hidden" name="valorVenda" value="25">
                            <input type="hidden" name="nomeProduto" value="">
                            <div class="mb-3" id="div_metodo_preparo">
                                <select class="custom-select w-50" name="metodo_preparo" id="metodo_preparo">
                                    <option value="graos">Grãos</option>
                                    <option value="moido">Moído</option>
                                    <option value="prensa">Prensa</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <div id="div_qnt_pacotes">   
                                    <select class="custom-select w-50" name="qnt_pacotes" id="qnt_pacotes">
                                        <option value="1">1 pacote de 250g</option>
                                        <option value="2">2 pacotes de 250g</option>
                                        <option value="3">3 pacotes de 250g</option>
                                        <option value="4">4 pacotes de 250g</option>
                                    </select>
                                </div>
                            </div>
                            <button type="submit" data-add="addCartAssinar" id="botao-clube-c" class="btn btn-md btn-outline-light cepConsulta mb-4 w-50">Adicionar ao carrinho</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col text-center">
                <div class="card shadow mb-4">
                    <img src="assets/nosso_clube-min-2.jpg" class="card-img-top" alt="">
                    <div class="card-body">
                        <h2 class="card-title mt-4" id="h2-price">R$<h1 id="h1-price">29</h1>+ frete*</h2>
                        <h5 class="card-title">Compra</h5>
                        <p class="card-text p-3">Está em dúvida? Você pode experimentar antes de assinar. Faça uma compra nossos cafés disponíveis e aproveite!</p>
                        <h6 class="card-title w-70 mb-3">Escolha como você vai querer seu café especial</h6>
                        <form id="comprar" action="" method="post">
                            <!-- <input type="hidden" name="idCompra" value="1"> -->
                            <input type="hidden" name="valorVenda" value="29">
                            <input type="hidden" name="nomeProduto" value="">
                            <div class="mb-3" id="div_metodo_preparo">
                                <select class="custom-select w-50" name="metodo_preparo" id="metodo_preparo">
                                    <option value="graos">Grãos</option>
                                    <option value="moido">Moído</option>
                                    <option value="prensa">Prensa</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <div id="div_qnt_pacotes">   
                                    <select class="custom-select w-50" name="qnt_pacotes" id="qnt_pacotes">
                                        <option value="1">1 pacote de 250g</option>
                                        <option value="2">2 pacotes de 250g</option>
                                        <option value="3">3 pacotes de 250g</option>
                                        <option value="4">4 pacotes de 250g</option>
                                    </select>
                                </div>
                            </div>
                            <button type="submit" data-add="addCartComprar" id="botao-comprar-c" class="btn btn-md btn-outline-light cepConsulta mb-4 w-50">Adicionar ao carrinho</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- <div class="col-md-6">
                <img id="img1" class="img-fluid no-gutter" src="assets/box.png" alt="">
            </div>
            <div class="col-md-6 justify-content-center text-center">
                <h2 id="h2-price">R$<h1 id="h1-price">25</h1>+ frete*</h2>
                <h5>Escolha como você quer o seu café especial.</h5>
                <div id="choice1" class="row mb-3 mt-3 align-self-center justify-content-center">
                    <div class="row offset-md-3">
                        <form class="form" action="" id="assinar" method="post">
                            <div class="form-group">
                                 <h5>Comprar</h5>
                                <input type="hidden" name="idCompra" value="2">
                                <input type="hidden" name="valorVenda" value="25">
                                <input type="hidden" name="nomeProduto" value="">
                                <div class="mb-3" id="div_metodo_preparo">
                                    <select class="custom-select w-100" name="metodo_preparo" id="metodo_preparo">
                                        <option value="graos">Grãos</option>
                                        <option value="moido">Moído</option>
                                    </select>
                                </div> 
                            </div>
                            <div class="form-group">
                                <div id="div_qnt_pacotes">   
                                    <select class="custom-select w-100" name="qnt_pacotes" id="qnt_pacotes">
                                        <option value="1">1 pacote de 250g</option>
                                        <option value="2">2 pacotes de 250g</option>
                                        <option value="3">3 pacotes de 250g</option>
                                        <option value="4">4 pacotes de 250g</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row align-items-center">
                                <button type="submit" target="_blank" data-add="addCartAssinar" id="botao-clube" class="btn btn-lg btn-outline-light">Adicionar assinatura ao carrinho</button>
                            </div>
                        </form>
                    </div>
                </div>                     
                <p>Mandamos para sua casa 1 pacotinho de café de 250g dentro de uma caixinha maneira!</p>
                <p>Será sempre 1 pacotinho de café especial, moído ou em grãos, de fazendas incríveis que produzem cafés de alta qualidade.</p>
                <p>Hoje mais de 85% dos pequenos produtores não conseguem atingir a pontuação necessária para cafés especiais. Ao assinar o nosso clube ou comprar os cafés de impacto, você ajuda o pequeno produtor a investir no seu negócio e produzir cafés cada vez melhores.</p>
                <p>Está em dúvida? Você pode experimentar antes de assinar comprando uma caixinha avulsa por <span>R$29,00 + Frete*.</span></p>
                <div id="choice2" class="row mb-3 mt-3 align-self-center justify-content-center">
                    <div class="row offset-md-3">
                        <form class="form" action="" id="comprar" method="post">
                            <div class="form-group">
                                <h5>Comprar</h5>
                                <input type="hidden" name="idCompra" value="1">
                                <input type="hidden" name="valorVenda" value="29">
                                <input type="hidden" name="nomeProduto" value="">
                                <div class="mb-3" id="div_metodo_preparo">
                                    <select class="custom-select w-100" name="metodo_preparo" id="metodo_preparo">
                                        <option value="graos">Grãos</option>
                                        <option value="moido">Moído</option>
                                    </select>
                                </div> 
                            </div>
                            <div class="form-group">
                                <div id="div_qnt_pacotes">   
                                    <select class="custom-select w-100" name="qnt_pacotes" id="qnt_pacotes">
                                        <option value="1">1 pacote de 250g</option>
                                        <option value="2">2 pacotes de 250g</option>
                                        <option value="3">3 pacotes de 250g</option>
                                        <option value="4">4 pacotes de 250g</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row align-items-center">
                                <button type="submit" target="_blank" data-add="addCartComprar" id="botao-comprar" class="btn btn-lg btn-outline-light">Adicionar compra ao carrinho</button>
                            </div>
                        </form>
                    </div>    
                </div>  
                <p><span>*O valor do frete será adicionado no checkout do Pagseguro.</span></p>
            </div>
        </div> -->
    </div>
    <small class="mt-5 p-3">* Frete especial de R$ 8,00 para a cidade do Rio de Janeiro.</small>    
</section>
<!-- end of section Nosso Clube Impacto -->

<!-- divisor divisor clube -->
<section id="divisor-clube" class="d-flex"> 
    <div class="container align-self-center">
        <div class="row">
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
            <div class="col-md-6 align-self-center text-center">
                <h2>Edição do mês</h2>
                <p>Todo mês enviaremos 1 pacotinho de 250g pra você.</p>
            </div>
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
        </div>
    </div>
</section>
<!-- end of divisor clube -->

<!-- section Nosso Clube Impacto -->
<section id="clube-impacto" class="fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 text-center">
                <h5>Café especial</h5>
                <p>O Sítio Serra dos Lopes, localizado no município de Manhumirim-MG, tem uma bela história de trabalho duro e paixão pelo café. O Délcio e a Sandra, um casal de produtores extremamente simpáticos, são a quarta geração de produtores da família e os responsáveis pela mudança de cultura na produção de café que herdaram, que até então, só produziam cafés como <i>commodity</i>. Quem chega ao Sítio, já é recebido com muito carinho pela Raposa, uma linda cadelinha da casa, e com o sorriso fácil do casal. Não é difícil perceber o profissionalismo e conhecimento avançado que eles têm sobre cafés especiais. Por isso trouxemos esse cafezão de lá. <a href="https://cafemerula.com.br/qrcode" id="qr">Confere aqui!</a></p>
                <div class="row">
                    <div class="col-md-12 text-center car-cafe-top">
                        <span id="car-cafe">Altitude</span> 
                        <h6>1140m</h6>
                        <span id="car-cafe">Variedade</span>
                        <h6>Catuaí vermelho IAC-785</h6>
                        <span id="car-cafe">Processo</span>
                        <h6>Natural</h6>
                        <span id="car-cafe">Secagem</span>
                        <h6>Terreiro de concreto</h6>
                        <span id="car-cafe">Notas</span>
                        <h6>Frutado, baunilha e melaço</h6>
                    </div>
                </div>
            </div>
            <div class="col-md-6" id="img-car-cafe">
                <img id="img2" class="img-fluid no-gutters" src="https://instagram.fsdu5-1.fna.fbcdn.net/v/t51.2885-15/e35/66840279_861369520894335_6503033290730253356_n.jpg?_nc_ht=instagram.fsdu5-1.fna.fbcdn.net&_nc_cat=103&_nc_ohc=OFy8nIojSAoAX9N6feQ&tp=18&oh=3a032a80ea267bcd363c74f2bc25c3ac&oe=5FDE5A1C" alt="">
            </div>
        </div>
    </div>
</section>
<!-- end of section Nosso Clube Impacto -->

<!-- Certifications -->
    <section id="certifications">
        <div class="container">
            <div class="row">
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/LogoMataMinas.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/utz.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/cafesbrasil.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/logo_header_pt.png" alt="">
                </div>
            </div>
        </div>
    </section>
<!-- end of Certifications -->
