<div class="espacos" id="espaco-contato">

</div>

<!-- divisor contato -->
<section id="divisor-contato" class="d-flex"> 
    <div class="container align-self-center">
        <div class="row">
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
            <div class="col-md-6 align-self-center text-center">
                <h2>Obrigado pela visita!</h2>
                <p>Como podemos te ajudar?</p>
            </div>
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
        </div>
    </div>
</section>
<!-- end of divisor contato -->

<!-- form contato -->
<section id="contato">
    <div class="row justify-content-center">
        <div class="col text-center">
            <p>Envie um e-mail para <strong>contato@cafemerula.com.br</strong> ou mande uma mensagem.</p>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                <form action="">
                    <div class="form-row">
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="nome-contato" placeholder="Nome" required>
                        </div>
                        <div class="col-md-6">
                            <div class="input-group">
                                <input type="text" class="form-control" id="email-contato" placeholder="E-mail" required>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <textarea class="form-control" id="textarea-contato" placeholder="Deixe sua mensagem" rows="8" required></textarea>
                    </div>
                    <div class="form-row">
                        <button type="button" id="botao-contato" class="btn btn-assinar btn-dark btn-lg btn-block">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- end of form contato -->