<!-- section home -->
<section id="home" class="d-flex">
    <div class="container align-self-center">
    <div class="row">
        <div class="col-md-12 capa">
            <img src="assets/merula_logo.png" alt="">
            <h1 id="titulo">MERULA</h1>
            <p id="sub-titulo">Cafés especiais de impacto</p>
            <p id="slogan">Café especial de verdade, direto do produtor para a sua casa.</p>
            <a href="/clube-de-impacto" class="btn btn-lg btn-outline-light btn-custom btn-assinar">
            Assinar
            </a>

        </div>
    </div>
    </div>
</section>
<!-- end of section home -->

<!-- section Nosso Clube -->
<section id="nosso-clube" class="fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <img class="img-fluid" src="assets/nosso_clube.jpg" alt="">
            </div>
            <div class="col-md-6 justify-content-center text-center">
                <h2>Nosso clube</h2>
                <p>Somos cariocas e apaixonados por café! Na nossa busca pelos melhores cafés do Brasil, encontramos pessoas incríveis que trabalham duro e vivem do cultivo do café. Porém, assim como elas, mais de 85% dos pequenos produtores não atingem a qualidade exigida dos cafés especiais.</p>
                <p>Nossa missão é levar o melhor do café pra você que é apaixonado por essa bebida maravilhosa e ajudar no desenvolvimento dos pequenos produtores familiares de café do Brasil.</p>
                <p>Nosso papel nessa cadeia de produção de café especial é compartilhar o conhecimento e nossa experiência com cafés especiais para os pequenos produtores.</p>
                <p>Por isso, levamos a vocês café incríveis e com propósito. Assine. Você será muito bem vindo no nosso Clube de Impacto!</p>
                <a href="/clube-de-impacto" class="btn btn-lg btn-outline-dark btn-custom btn-assinar">
                Assinar
                </a>
            </div>
        </div>
    </div>
</section>
<!-- end of section Nosso Clube -->

<!-- section Processo -->
<section id="processo">
    <div class="container-fluid">
        <div class="row align-self-center align-items-center">
            <div class="col-md-3 ml-auto text-center">
                <h3 id="folha"><i class="fas fa-leaf fa-2x"></i></h3>
                <h4>colheita</h4>
                <p>Pegamos a estrada e selecionamos os melhores grãos de fazendas certificadas de café especial.</p>
            </div>
            <div class="col-md-3 justify-content-center text-center">
                <h3 id="bean"><img class="img-fluid" src="assets/coffee-beans.svg" alt=""></h3>
                <h4>torra</h4>
                <p>Torramos artesanalmente, aqui no Rio, toda semana. Assim, o café fica sempre fresquinho!</p>
            </div>
            <div class="col-md-3 justify-content-center text-center">
                <h3 id="box"><i class="fas fa-box fa-2x"></i></h3>
                <h4>Caixinha</h4>
                <p>Você pode escolher receber seu café especial moído ou em grãos, pra apreciar do seu jeito.</p>
            </div>
            <div class="col-md-3 justify-content-center text-center">
                <h3 id="cup"><i class="fas fa-mug-hot fa-2x"></i></h3>
                <h4>xícara</h4>
                <p>Aprecie seu café fresquinho! Recomendamos 70g de pó para 1L de água para cafezinho coado.</p>
            </div>
        </div>
    </div>
</section>
<!-- end of section Processo -->

<!-- Divisor -->
<section id="divisor" class="d-flex"> 
    <div class="container align-self-center">
        <div class="row">
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
            <div class="col-md-6 align-self-center text-center">
                <h2>Edição do mês</h2>
                <p>Todo mês enviamos um pacotinho de 250g pra você</p>
            </div>
            <div class="col-md-3 align-self-center text-center">
                <hr>
            </div>
        </div>
    </div>
</section>
<!-- end of divisor -->

<!-- section edition -->
<section id="edition">
    <div class="container">
        <div class="row">
            <div class="col-md-4 text-center">
                <h2>Café Especial</h2>
                <p>Hoje, Gilmar e mais 3 irmãos trabalham em suas lavouras no Sítio Boa Vista, cada um cuidando de uma parte dessa terra que já está na terceira geração de uma família de cafeicultores. Gilmar procura mater a cultura de sempre trabalharem juntos e preservarem o meio ambiente e passar para suas 2 filhas, que já expressam o desejo de continuar trabalhando com café e garantir a sucessão familiar nesta atividade. <a id="qr" href="">Confere aqui!</a></p>
                <a href="" class="btn btn-md btn-outline-dark btn-custom btn-assinar text-center">
                Assinar
                </a>
            </div>
            <div class="col-md-8">
                <img src="assets/indaia.jpeg" alt="">
            </div>
        </div>
    </div>
</section>
<!-- end of section edition -->

<!-- Certifications -->
    <section id="certifications">
        <div class="container">
            <div class="row">
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/LogoMataMinas.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/utz.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/cafesbrasil.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/logo_header_pt.png" alt="">
                </div>
            </div>
        </div>
    </section>
<!-- end of Certifications -->