<div id="carrinho">
  <div class="espacos" id="espaco-clube-impacto">

  </div>
  <div class="espacos" id="espaco-clube-impacto">

    </div>
  <div class="container">
    <div class="row">
      <!-- <div class="col-1"></div> -->
      <div class="col">
        <div class="card" id="card-login">
          <div class="card-body">
          <h2>Faça seu login</h2>
            <form action="" id="formLogin">
                <div class="row form-group">
                  <div class="col">
                    <label for="emailLogin">Email</label>
                    <input type="email" class="form-control" name="emailLogin" id="emailLogin" placeholder="Digite seu email">
                  </div>
                </div>
                <div class="row form-group">
                  <div class="col">
                    <label for="senhaLogin">Senha</label>
                    <input type="password" class="form-control" name="senhaLogin" id="senhaLogin" placeholder="Digite sua senha">
                  </div>
                </div>
                <div class="row">
                  <div class="col">
                    <button type="submit" class="btn btn-md btn-outline-dark btn-block cepConsulta mb-3">Login</button>
                  </div>
                </div>
                <span id="loading"></span>
            </form>
            <p>Ainda não tem cadastro?</p>
            <div class="row">
              <div class="col">
                <a href="/cadastro" class="btn btn-md btn-outline-dark btn-block">Cadastrar</a>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <a href="/facebook" class="btn btn-md btn-primary btn-block">Facebook</a>
              </div>
              <div class="col">
                <a href="/google" class="btn btn-md btn-danger btn-block">Google</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- <div class="col-1"></div> -->
    </div>
    <div class="espacos" id="espaco-clube-impacto">

    </div>
  </div>
</div>