<section id="home" class="d-flex">
    <div class="container align-self-center">
    <div class="row">
        <div class="col-md-12 capa-man">
            <!-- <img src="assets/merula_logo.png" alt="">
            <h1 id="titulo-man" width="50%">MERULA</h1>
            <p id="sub-titulo-man">Cafés especiais de impacto</p> -->
            <p><i class="fas fa-7x fa-exclamation-triangle"></i></p>
            <h4>Estamos reformulando algumas coisas por aqui.</h4>
            <div>
                <p>Para assinar ou comprar, entre em contato conosco por Direct ou Whatsapp:</p>
                <div id="destaque">
                    <p>Aproveite o frete especial para a cidade do Rio de Janeiro por R$8,00</p>
                </div>
                <ul class="navbar-nav">
                    <li class="nav-item align-self-center" id="icon-social">
                        <a class="social-icon" href="<?php echo SOCIAL['instagram_page']; ?>" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
                        <a class="social-icon" href="<?php echo SOCIAL['facebook_page']; ?>" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
                        <a class="social-icon" href="<?php echo SOCIAL['whatsapp_api']; ?>" target="_blank"><i class="fab fa-whatsapp fa-2x"></i></a>
                    </li>
                </ul>
            </div>
            <!-- <a href="/clube-de-impacto" class="btn btn-lg btn-outline-light btn-custom btn-assinar">
            Assinar
            </a> -->

        </div>
    </div>
    </div>
</section>
<!-- end of section home -->