<div class="espacos" id="espaco-clube-impacto">

</div>

<div class="container">
    <div class="row">
        <h2 class="display-4">Detalhes do faturamento</h2>
        <div class="col-md-4 order-md-2 mb-4">
            <h4>Seu pedido</h4>
            <h5>Escolha a forma de pagamento</h5>
            <div class="custom-control custom-radio">
                <input type="radio" name="paymentMethod" class="custom-control-input" id="paymentMethod" value="creditCard" onclick="tipoPagamento('creditCard')" checked required>
                <label class="custom-control-label" for="paymentMethod">Cartão de crédito</label><br>
            </div>
            <div class="custom-control custom-radio">
                <input type="radio" name="paymentMethod" class="custom-control-input" id="boleto" value="boleto" onclick="tipoPagamento('boleto')" required>
                <label class="custom-control-label" for="boleto">Boleto</label>
            </div>
            <div class="row">
                <label for="numCartao">Número do cartão</label>
                <div class="input-group">
                    <input class="form-control" type="text" name="numCartao" id="numCartao" class="creditCard">
                    <div class="input-group-append">
                        <span class="bandeira-cartao"></span>
                    </div>
                </div>
                <span id="msg"></span>
            </div>
            <div class="row">
                <div class="col" id="div_form_input">
                    <label for="mesValidade">Mês de Validade</label>
                    <input class="form-control" type="text" name="mesValidade" id="mesValidade" maxlength="2" value="12" class="creditCard">
                </div>
                <div class="col" id="div_form_input">
                    <label for="anoValidade">Ano de Validade</label>
                    <input class="form-control" type="text" name="anoValidade" id="anoValidade" maxlength="4" value="2030" class="creditCard">
                </div>
            </div>
            <div class="row">
                <div class="col" id="div_form_input">
                    <label for="cvvCartao">CVV</label>
                    <input class="form-control" type="text" name="cvvCartao" id="cvvCartao" maxlength="3" value="123" class="creditCard">
                </div>
                <div class="col" id="div_form_input">
                    <label for="bandeiraCartao">Bandeira</label>
                    <input class="form-control" type="text" name="bandeiraCartao" id="bandeiraCartao" class="creditCard">
                </div>
            </div>
        </div>
    
        
        <div id="div-formPagamento" class="col-md-8 order-md-1">
            <span class="endereco" data-endereco="<?php echo PAGSEGURO['url_site']; ?>"></span>

            <form name="formPagamento" action="<?php echo PAGSEGURO['url_site'] . 'checkout'; ?>" id="formPagamento">
            
                <!-- campo oculto para manipulacao interna -->
                <input type="hidden" name="paymentMethod" id="paymentMethod" value="creditCard">

                <input type="hidden" name="receiverEmail" id="receiverEmail" value="<?php echo PAGSEGURO['email_loja']; ?>">

                <input type="hidden" name="currency" id="currency" value="<?php echo PAGSEGURO['moeda']; ?>">

                <input type="hidden" name="extraAmount" id="extraAmount" value="">

                <input type="hidden" name="itemId1" id="itemId1" value="0001">

                <input type="hidden" name="itemDescription1" id="itemDescription1" value="Curso de PHP Orientado a Objetos">

                <input type="hidden" name="itemAmount1" id="itemAmount1" value="600.00">

                <input type="hidden" name="itemQuantity1" id="itemQuantity1" value="1">

                <input type="hidden" name="notificationURL" id="notificationURL" value="<?php echo PAGSEGURO['url_notificacao']; ?>">

                <input type="hidden" name="reference" id="reference" value="12">

                <input type="hidden" name="amount" id="amount" value="600">

                <input type="hidden" name="noIntInstalQuantity" id="noIntInstalQuantity" value="2">

                <h4>Dados do assinante</h4>

                <div class="col mb-3" id="div_form_input">
                    <label for="senderName">Nome</label>
                    <input class="form-control" type="text" name="senderName" id="senderName" placeholder="Nome completo" value="jose comprador" required>
                    <div class="invalid-feedback">
                    Informe seu nome completo.
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-6 mb-3" id="div_form_input">
                        <label for="creditCardHolderBirthDate">Data de Nascimento</label>
                        <input class="form-control" type="text" name="creditCardHolderBirthDate" id="creditCardHolderBirthDate" placeholder="Data de Nascimento. Ex: 12/12/1912" value="14/01/1989" required>
                    </div>
                    <div class="col-md-6 mb-3" id="div_form_input">
                        <label for="senderCPF">CPF</label>
                        <input class="form-control" type="text" name="senderCPF" id="senderCPF" placeholder="CPF sem traço" value="10730297780" required>
                    </div>    
                </div>

                <div class="col mb-3" id="div_form_input">
                    <label for="senderEmail">E-mail</label>
                    <input class="form-control" type="text" name="senderEmail" id="senderEmail" placeholder="Digite seu e-mail" value="c06295104531696264383@sandbox.pagseguro.com.br" required>
                    <div class="invalid-feedback">
                    Informe seu e-mail.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3" id="div_form_input">
                        <label for="senderAreaCode">DDD</label>
                        <input class="form-control" type="text" name="senderAreaCode" id="senderAreaCode" placeholder="DDD" value="21" required>
                    </div>
                    <div class="col" id="div_form_input">
                        <label for="senderPhone">Telefone</label>
                        <input class="form-control" type="text" name="senderPhone" id="senderPhone" placeholder="Somente número" value="982019916" required>
                    </div>    
                </div>

                <h4>Endereço de Entrega</h4>

                <input type="hidden" name="shippingAddressRequired" id="shippingAddressRequired" value="true" required>

                <div class="row">
                    <div class="col-md-4" id="div_form_input">
                        <label for="shippingAddressPostalCode">CEP</label>
                        <input class="form-control" type="text" name="shippingAddressPostalCode" id="shippingAddressPostalCode" placeholder="CEP sem traço" value="22795641">
                    </div>
                    <div class="col-md-8 mb-3" id="div_form_input">
                        <label for="shippingAddressStreet">Logradouro</label>
                        <input class="form-control" type="text" name="shippingAddressStreet" id="shippingAddressStreet" placeholder="Av. Rua" value="av henfil">
                        <div class="invalid-feedback">
                        Informe o logradouro.
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2" id="div_form_input">
                        <label for="shippingAddressNumber">Número</label>
                        <input class="form-control" type="text" name="shippingAddressNumber" id="shippingAddressNumber" placeholder="Número" value="25">
                    </div>
                    <div class="col-md-5" id="div_form_input">
                        <label for="shippingAddressComplement">Complemento</label>
                        <input class="form-control" type="text" name="shippingAddressComplement" id="shippingAddressComplement" placeholder="Complemento" value="bl2">
                    </div>
                    <div class="col-md-5" id="div_form_input">
                        <label for="shippingAddressDistrict">Bairro</label>
                        <input class="form-control" type="text" name="shippingAddressDistrict" id="shippingAddressDistrict" placeholder="Bairro" value="recreio">
                    </div>    
                </div>

                <div class="row">
                    <div class="col-md-5" id="div_form_input">
                        <label for="shippingAddressCity">Cidade</label>
                        <input class="form-control" type="text" name="shippingAddressCity" id="shippingAddressCity" placeholder="Cidade" value="rio de janeiro">
                    </div>
                    <div class="col-md-3" id="div_form_input">
                        <label for="shippingAddressState">Estado</label>
                        <input class="form-control" type="text" name="shippingAddressState" id="shippingAddressState" placeholder="Sigla do Estado" value="RJ">
                    </div>
                    <div class="col-md-4" id="div_form_input">
                        <label for="shippingAddressCountry">País</label>
                        <input class="form-control" type="text" name="shippingAddressCountry" id="shippingAddressCountry" value="BRL">
                    </div>   
                </div>

                <h5>Frete</h5>

                <div class="custom-control custom-radio">
                    <input type="radio" name="shippingType" id="pac" class="custom-control-input" value="1">
                    <label class="custom-control-label" for="pac">PAC</label><br>
                </div>
                <div class="custom-control custom-radio">
                    <input type="radio" name="shippingType" id="sedex" class="custom-control-input" value="2">
                    <label class="custom-control-label" for="sedex">SEDEX</label><br>
                </div>
                <div class="custom-control custom-radio">
                    <input type="radio" name="shippingType" id="semfrete" class="custom-control-input" value="3" checked>
                    <label class="custom-control-label" for="semfrete">Sem frete</label><br>
                </div>

                <label>Valor Frete</label>
                <input type="text" name="shippingCost" id="senderCPF" placeholder="Preço do frete. Ex: 2.10" value=""><br><br>

                <h2 class="creditCard">Dados do Cartão</h2>

                <label class="creditCard">Quantidades de Parcelas</label>
                <select name="qntParcelas" id="qntParcelas" class="creditCard select-qnt-parcelas">
                    <option value="" class="creditCard">Selecione</option>
                </select><br><br>

                <label class="creditCard">Valor Parcelas</label>
                <input type="text" name="valorParcelas" id="valorParcelas" class="creditCard"><br><br>

                <label class="creditCard">CPF do Cartão</label>
                <input type="text" name="creditCardHolderCPF" id="creditCardHolderCPF" placeholder="CPF sem traço" value="10730297780" class="creditCard" required><br><br>

                <label class="creditCard">Nome no Cartão</label>
                <input type="text" name="creditCardHolderName" id="creditCardHolderName" placeholder="Nome igual ao escrito no cartão" value="jose comprador" class="creditCard" required><br><br>

                <input type="hidden" name="tokenCartao" id="tokenCartao"><br><br>

                <input type="hidden" name="hashCartao" id="hashCartao"><br><br>

                <h2 class="creditCard">Endereço do Cartão</h2>

                <label class="creditCard">Logradouro</label>
                <input type="text" name="billingAddressStreet" id="billingAddressStreet" placeholder="Av. Rua" value="av henfil" class="creditCard"><br><br>

                <label class="creditCard">Número</label>
                <input type="text" name="billingAddressNumber" id="billingAddressNumber" placeholder="Número" value="25" class="creditCard"><br><br>

                <label class="creditCard">Complemento</label>
                <input type="text" name="billingAddressComplement" id="billingAddressComplement" placeholder="Complemento" value="bl2" class="creditCard"><br><br>

                <label class="creditCard">Bairro</label>
                <input type="text" name="billingAddressDistrict" id="billingAddressDistrict" placeholder="Bairro" value="recreio" class="creditCard"><br><br>

                <label class="creditCard">CEP</label>
                <input type="text" name="billingAddressPostalCode" id="billingAddressPostalCode" placeholder="CEP sem traço" value="21555300" class="creditCard"><br><br>

                <label class="creditCard">Cidade</label>
                <input type="text" name="billingAddressCity" id="billingAddressCity" placeholder="Cidade" value="rio de janeiro" class="creditCard"><br><br>

                <label class="creditCard">Estado</label>
                <input type="text" name="billingAddressState" id="billingAddressState" placeholder="Sigla do Estado" value="RJ" class="creditCard"><br><br>

                <label class="creditCard">País</label>
                <input type="text" name="billingAddressCountry" id="billingAddressCountry" value="BRL" value="Brasil" class="creditCard"><br><br>        

                <input type="submit" name="btnComprar" id="btnComprar" value="Comprar">
            </form>
        </div>    
    </div>        
</div>

<!-- cria as imagens dinamicamente por meio do srcipt.js -->
<!-- <div class="meio-pag"></div> -->