<div class="espacos" id="espaco-clube-impacto">

</div>

<div class="container">
<span class="endereco" data-endereco="<?php echo PAGSEGURO['url_site']; ?>"></span>
    <div class="row">
        <h2 class="display-4">Detalhes do faturamento</h2>
        <div class="col-md-4 order-md-2 mb-4">
            <h4>Seu pedido</h4>
            <h5>Escolha a forma de pagamento</h5>      
            <form name="formPagamento" action="<?php echo PAGSEGURO['url_site'] . 'checkout'; ?>" id="formPagamento">
            <div class="custom-control custom-radio">
                <input type="radio" name="paymentMethod" class="custom-control-input" id="paymentMethod1" value="creditCard" onclick="tipoPagamento('creditCard')" required>
                <label class="custom-control-label" for="paymentMethod1">Cartão de crédito</label><br>
            </div>
            <div class="custom-control custom-radio">
                <input type="radio" name="paymentMethod" class="custom-control-input" id="paymentMethod2" value="boleto" onclick="tipoPagamento('boleto')" required>
                <label class="custom-control-label" for="paymentMethod2">Boleto</label>
            </div>

            <h5>Frete</h5>

                <div class="custom-control custom-radio">
                    <input type="radio" name="shippingType" id="pac" class="custom-control-input" value="1">
                    <label class="custom-control-label" for="pac">PAC</label><br>
                </div>
                <div class="custom-control custom-radio">
                    <input type="radio" name="shippingType" id="sedex" class="custom-control-input" value="2">
                    <label class="custom-control-label" for="sedex">SEDEX</label><br>
                </div>
                <div class="custom-control custom-radio">
                    <input type="radio" name="shippingType" id="semfrete" class="custom-control-input" value="3">
                    <label class="custom-control-label" for="semfrete">Sem frete</label><br>
                </div>
                <div>
                    <label>Valor Frete</label>
                    <input type="text" name="shippingCost" id="shippingCost" placeholder="Preço do frete. Ex: 2.10" class="form-control">
                </div>

            <div class="row" id="formCreditCardOption">
                <div class="row">
                    <label for="numCartao">Número do cartão</label>
                    <div class="input-group">
                        <input class="form-control" type="text" name="numCartao" id="numCartao" class="creditCard">
                        <div class="input-group-append">
                            <span class="input-group-text bandeira-cartao"></span>
                        </div>
                    </div>
                    <span id="msg"></span>
                </div>
                <div class="row">
                    <div class="col" id="div_form_input">
                        <label for="mesValidade">Mês de Validade</label>
                        <input class="form-control" type="text" name="mesValidade" id="mesValidade" maxlength="2" value="12" class="creditCard">
                    </div>
                    <div class="col" id="div_form_input">
                        <label for="anoValidade">Ano de Validade</label>
                        <input class="form-control" type="text" name="anoValidade" id="anoValidade" maxlength="4" value="2030" class="creditCard">
                    </div>
                </div>
                <div class="row">
                    <div class="col" id="div_form_input">
                        <label for="cvvCartao">CVV</label>
                        <input class="form-control" type="text" name="cvvCartao" id="cvvCartao" maxlength="3" value="123" class="creditCard">
                    </div>
                    <div class="col" id="div_form_input">
                        <label for="bandeiraCartao">Bandeira</label>
                        <input class="form-control" type="text" name="bandeiraCartao" id="bandeiraCartao" class="creditCard">
                    </div>
                </div>
                <div class="row">
                    <div class="col" id="div_form_input">
                        <label for="creditCardHolderName">Nome escrito no cartão</label>
                        <input class="form-control" type="text" name="creditCardHolderName" id="creditCardHolderName" placeholder="Nome igual ao escrito no cartão" value="Jonathas Batista" class="creditCard" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col" id="div_form_input">
                        <label for="creditCardHolderCPF">CPF do dono do cartão</label>
                        <input class="form-control" type="text" name="creditCardHolderCPF" id="creditCardHolderCPF" placeholder="CPF sem traço" value="10730297780" class="creditCard" required>
                    </div>

                    <input type="hidden" name="tokenCartao" id="tokenCartao">
                </div>
                <div class="row">
                    <div class="row" id="subtotal"></div>
                    <div class="row">
                        <input type="text" name="amount" id="amount" class="form-control">
                    </div>
                    <div class="row">
                    <div class="col" id="div_form_input">
                        <label for="qntParcelas">Nº de parcelas</label>
                        <select class="custom-select d-block w-100" name="qntParcelas" id="qntParcelas" class="creditCard">
                            <option value="" class="creditCard">Selecione</option>
                        </select>
                    </div>
                    <div class="col" id="div_form_input">
                        <label for="valorParcelas">Valor Parcelas</label>
                        <input class="form-control" type="text" name="valorParcelas" id="valorParcelas" class="creditCard">
                    </div>
                    </div>
                </div>
            </div>

            <input type="hidden" name="hashCartao" id="hashCartao">

            <div class="form-row" id="div_form_input">
                <input class="btn btn-assinar btn-dark btn-lg btn-block" type="submit" name="btnComprar" id="btnComprar" value="Comprar">
            </div>  
        </div>
        
        <div id="div-formPagamento" class="col-md-8 order-md-1">
            
                <!-- campo oculto para manipulacao interna -->
                <!-- <input type="hidden" name="paymentMethod" id="paymentMethod" value="creditCard" checked> -->

                <input type="hidden" name="receiverEmail" id="receiverEmail" value="<?php echo PAGSEGURO['email_loja']; ?>">

                <input type="hidden" name="currency" id="currency" value="<?php echo PAGSEGURO['moeda']; ?>">

                <input type="hidden" name="extraAmount" id="extraAmount" value="">

                <input type="hidden" name="itemId1" id="itemId1" value="0001">

                <input type="hidden" name="itemDescription1" id="itemDescription1" value="Curso de PHP Orientado a Objetos">

                <input type="hidden" name="itemAmount1" id="itemAmount1" value="29.00">

                <input type="hidden" name="itemQuantity1" id="itemQuantity1" value="1">

                <input type="hidden" name="notificationURL" id="notificationURL" value="<?php echo PAGSEGURO['url_notificacao']; ?>">

                <input type="hidden" name="reference" id="reference" value="12">

                <input type="hidden" name="noIntInstalQuantity" id="noIntInstalQuantity" value="2">

                <input type="hidden" name="amountPerPayment" id="amountPerPayment" value="25.00">

                <input type="hidden" name="codePlan" id="codePlan">

                <h4>Dados pessoais</h4>

                <div class="col mb-3" id="div_form_input">
                    <label for="senderName">Nome</label>
                    <input class="form-control" type="text" name="senderName" id="senderName" placeholder="Nome completo" value="Jonathas Batista" required>
                    <div class="invalid-feedback">
                    Informe seu nome completo.
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-6 mb-3" id="div_form_input">
                        <label for="creditCardHolderBirthDate">Data de Nascimento</label>
                        <input class="form-control" type="text" name="creditCardHolderBirthDate" id="creditCardHolderBirthDate" placeholder="Data de Nascimento. Ex: 12/12/1912" value="14/01/1989" required>
                    </div>
                    <div class="col-md-6 mb-3" id="div_form_input">
                        <label for="senderCPF">CPF</label>
                        <input class="form-control" type="text" name="senderCPF" id="senderCPF" placeholder="CPF sem traço" value="10730297780" required>
                    </div>    
                </div>

                <div class="col mb-3" id="div_form_input">
                    <label for="senderEmail">E-mail</label>
                    <input class="form-control" type="text" name="senderEmail" id="senderEmail" placeholder="Digite seu e-mail" value="batista.jonathas@sandbox.pagseguro.com.br" required>
                    <div class="invalid-feedback">
                    Informe seu e-mail.
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3" id="div_form_input">
                        <label for="senderAreaCode">DDD</label>
                        <input class="form-control" type="text" name="senderAreaCode" id="senderAreaCode" placeholder="DDD" value="21" required>
                    </div>
                    <div class="col" id="div_form_input">
                        <label for="senderPhone">Telefone</label>
                        <input class="form-control" type="text" name="senderPhone" id="senderPhone" placeholder="Somente número" value="982019916" required>
                    </div>    
                </div>

                <h4>Endereço</h4>

                <input type="hidden" name="shippingAddressRequired" id="shippingAddressRequired" value="true">

                <div class="row">
                    <div class="col-md-4" id="div_form_input">
                        <label for="billingAddressPostalCode">CEP</label>
                        <input class="form-control" type="text" name="billingAddressPostalCode" id="billingAddressPostalCode" placeholder="CEP sem traço">
                    </div>
                    <div class="col-md-8 mb-3" id="div_form_input">
                        <label for="billingAddressStreet">Logradouro</label>
                        <input class="form-control" type="text" name="billingAddressStreet" id="billingAddressStreet" placeholder="Logradouro" readonly>
                        <div class="invalid-feedback">
                        Informe o logradouro.
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2" id="div_form_input">
                        <label for="billingAddressNumber">Número</label>
                        <input class="form-control" type="text" name="billingAddressNumber" id="billingAddressNumber" placeholder="Número">
                    </div>
                    <div class="col-md-5" id="div_form_input">
                        <label for="billingAddressComplement">Complemento</label>
                        <input class="form-control" type="text" name="billingAddressComplement" id="billingAddressComplement" placeholder="Complemento">
                    </div>
                    <div class="col-md-5" id="div_form_input">
                        <label for="billingAddressDistrict">Bairro</label>
                        <input class="form-control" type="text" name="billingAddressDistrict" id="billingAddressDistrict" placeholder="Bairro" readonly>
                    </div>    
                </div>
                <div class="row">
                    <div class="col-md-5" id="div_form_input">
                        <label for="billingAddressCity">Cidade</label>
                        <input class="form-control" type="text" name="billingAddressCity" id="billingAddressCity" placeholder="Cidade" readonly>
                    </div>
                    <div class="col-md-3" id="div_form_input">
                        <label for="billingAddressState">Estado</label>
                        <input class="form-control" type="text" name="billingAddressState" id="billingAddressState" placeholder="Sigla do Estado" readonly>
                    </div>
                    <div class="col-md-4" id="div_form_input">
                        <label for="billingAddressCountry">País</label>
                        <input class="form-control" type="text" name="billingAddressCountry" id="billingAddressCountry" readonly>
                    </div>   
                </div>

                <div class="custom-control custom-checkbox">
                    <input type="checkbox" name="shippingAdress" class="custom-control-input" id="shippingAdressOther" value="shippingAdressOther">
                    <label class="custom-control-label" for="shippingAdressOther">Endereço de entrega diferente</label><br>
                </div>

                <div class="row" id="formShippingAdressOption">
                    <div class="row" class="creditCard">
                        <div class="col-md-4" id="div_form_input">
                            <label for="shippingAddressPostalCode" class="creditCard">CEP</label>
                            <input class="form-control" type="text" name="shippingAddressPostalCode" id="shippingAddressPostalCode" placeholder="CEP sem traço">
                        </div>
                        <div class="col-md-8 mb-3" id="div_form_input">
                            <label for="shippingAddressStreet" class="creditCard">Logradouro</label>
                            <input class="form-control" type="text" name="shippingAddressStreet" id="shippingAddressStreet" placeholder="Av. Rua" readonly>
                            <div class="invalid-feedback">
                            Informe o logradouro.
                            </div>
                        </div>
                    </div>

                    <div class="row" class="creditCard">
                        <div class="col-md-2" id="div_form_input">
                            <label for="shippingAddressNumber" class="creditCard">Número</label>
                            <input class="form-control" type="text" name="shippingAddressNumber" id="shippingAddressNumber" placeholder="Número">
                        </div>
                        <div class="col-md-5" id="div_form_input">
                            <label for="shippingAddressComplement" class="creditCard">Complemento</label>
                            <input class="form-control" type="text" name="shippingAddressComplement" id="shippingAddressComplement" placeholder="Complemento">
                        </div>
                        <div class="col-md-5" id="div_form_input">
                            <label for="shippingAddressDistrict" class="creditCard">Bairro</label>
                            <input class="form-control" type="text" name="shippingAddressDistrict" id="shippingAddressDistrict" placeholder="Bairro" readonly>
                        </div>    
                    </div>

                    <div class="row" class="creditCard">
                        <div class="col-md-5" id="div_form_input">
                            <label for="shippingAddressCity" class="creditCard">Cidade</label>
                            <input class="form-control" type="text" name="shippingAddressCity" id="shippingAddressCity" placeholder="Cidade" readonly>
                        </div>
                        <div class="col-md-3" id="div_form_input">
                            <label for="shippingAddressState" class="creditCard">Estado</label>
                            <input class="form-control" type="text" name="shippingAddressState" id="shippingAddressState" placeholder="Sigla do Estado" readonly>
                        </div>
                        <div class="col-md-4" id="div_form_input">
                            <label for="shippingAddressCountry" class="creditCard">País</label>
                            <input class="form-control" type="text" name="shippingAddressCountry" id="shippingAddressCountry" readonly>
                        </div>   
                    </div>
                </div>
            </form>
        </div>    
    </div>        
</div>

<!-- cria as imagens dinamicamente por meio do srcipt.js -->
<!-- <div class="meio-pag"></div> -->