<div class="espacos" id="espaco-clube-impacto"></div>

<div class="container mb-5">
    <div id="titleCad" class="row mt-3 mb-3">
        <div class="col text-center">
            <h2 class="display-6">Política de Privacidade</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p>A Política de Privacidade e Segurança da Informação é elaborada para reafirmar nosso compromisso com as informações que coletamos dos usuários.
            Não enviamos spam, nem repassamos as suas informações cadastrais. Qualquer informação fornecida pelos usuários será coletada e guardada de acordo com os mais rígidos padrões de segurança e confiabilidade. Envidaremos nossos melhores esforços na manutenção da integridade das informações que nos forem fornecidas.
            Coletamos e processamos dados apenas para fins específicos e limitados, como por exemplo, podemos coletar e usar dados para fornecer a você nossos produtos ou serviços, fazer cobranças de produtos ou serviços solicitados por você, verificar seu crédito, informá-lo sobre produtos e serviços que acreditamos ser de seu interesse. nos comunicarmos com você ou utilizá-los em estatísticas internas.</p>
            <p>Todo o seu processo de compra e cadastramento é 100% seguro, respaldado por empresas de segurança e certificação mundialmente reconhecidas. Todas as informações são criptografadas e navegam em forma de código pela web, o que torna praticamente impossível o acesso de terceiros a tais informações.

            O número do seu cartão de crédito só é utilizado no ato da sua compra e não fica registrado no nosso sistema. As únicas informações que guardamos são seus dados pessoais. Cuidamos das suas informações em todas as etapas do processo de compra e navegação pelo site. Em caso de dúvidas estaremos a sua disposição para atendê-lo.</p>
        </div>    
    </div>
    <div id="titleCad" class="row mt-3 mb-3">
        <div class="col text-center">
            <h2 class="display-6">Política de compras e envio</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p>Para você aproveitar tudo de bom que o café tem a oferecer, é importante que a torra esteja o mais recente possível. Por isso, temos que fechar os pedidos em 4 lotes por mês e dessa maneira garantir que você aprecie seu café dentro da semana que foi torrado. Visto que o serviço do PAC demora em média 10 dias pra qualquer lugar do Brasil, seu pedido deve estar, no máximo, em 15 dias na sua casa. Estamos melhorando para que esse prazo seja cada vez mais curto e seu café cada vez melhor.</p>
            <p>Formas de Pagamento:
            Você pode efetuar o pagamento através dos cartões de crédito: Visa, Mastercard, Elo, Amex, Hiper, HiperCard (PayPal).

            Após finalizar a sua compra, as opções de pagamento e parcelamento não poderão ser alteradas.</p>

            <p>Prazo de entrega:
            O prazo de entrega será contado após a confirmação de seus dados cadastrais e pagamento, iniciando a contagem sempre no dia útil seguinte a confirmação do pagamento.

            A partir da confirmação, temos um prazo de 5 dias úteis para processá-lo. O restante do prazo é por conta dos Correios.

            Recebimento do produto:
            Ao receber o produto é importante que você confira a mercadoria no ato da entrega. Caso deseje cancelar, devolver ou trocar o produto por algum motivo, entre em contato através do e-mail: contato@cafemerula.com.br. No prazo de 5 dias úteis retornaremos sua solicitação. No ato da devolução, deverá ser encaminhado também a nota fiscal do produto.</p>
            <p>Preços:
            Os preços a serem pagos pelos itens solicitados são aqueles exibidos no site na data da realização do pedido.
            As taxas de entrega serão calculadas principalmente em função do volume do pedido e do método de entrega selecionado.
            Reservamos o direito de modificar os preços dos produtos e as taxas de entrega a qualquer momento.</p>
            <p>Limitação de responsabilidade:
            As imagens e os textos que ilustram e descrevem os produtos na nossa loja virtual são não contratuais e servem apenas para fins informativos.</p>
        </div>    
    </div>
</div>