<div class="espacos" id="espaco-clube-impacto">

</div>
<div class="container mt-5 mb-5">
    <section id="divisor-clube" class="d-flex"> 
        <div class="container align-self-center">
            <div class="row">
                <div class="col-md-3 align-self-center text-center">
                    <hr>
                </div>
                <div class="col-md-6 align-self-center text-center">
                    <h2>Nossos Produtores</h2>
                    <p>Conheça as histórias dos nossos produtores contadas por eles</p>
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <hr>
                </div>
            </div>
        </div>
    </section>
    <!-- end of divisor clube -->
    <div>
        <div class="embed-responsive embed-responsive-1by1">
            <iframe class="embed-responsive-item" src="assets/serradoslopes_portifolio.pdf" width="800px" height="2100px" allowfullscreen></iframe>
        </div> 
    </div>
</div>