<div class="espacos">

</div>

<!-- Sobre nos -->
<section id="nosso-clube" class="fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <img class="img-fluid" src="assets/nosso_clube.jpg" alt="">
            </div>
            <div class="col-md-6 justify-content-center text-center">
                <h2>Sobre nós</h2>
                <p>Somos uma empresa carioca e resolvemos fazer da nossa paixão, um negócio. Como netos de produtores de café da região das Matas de Minas, passamos a infância nas lavouras. Por isso resolvemos trazer um pouquinho desse mundo pra nossa cidade.</p>
                <p>Resolvemos ir além e aprender mais sobre os melhores cafés. Foi aí que decidimos trazer, de fazendas certificadas, os grãos de café especial para torrarmos por aqui.</p>
                <p>Na nossa busca pelos melhores cafés do Brasil, encontramos pessoas incríveis que trabalham duro e vivem do cultivo do café. E, assim como elas, mais de 85% dos pequenos produtores não atingem a qualidade exigida dos cafés especiais.</p>
                <p>Nossa missão é levar o melhor do café pra você que é apaixonado por essa bebida maravilhosa e ajudar no desenvolvimento dos pequenos produtores familiares de café do Brasil. </p>
            </div>
        </div>
    </div>
</section>
<!-- end of sobre nos -->

<!-- Certifications -->
    <section id="certifications">
        <div class="container">
            <div class="row">
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/LogoMataMinas.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/utz.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/cafesbrasil.png" alt="">
                </div>
                <div class="col-md-3 align-self-center text-center">
                    <img src="assets/logo_header_pt.png" alt="">
                </div>
            </div>
        </div>
    </section>
<!-- end of Certifications -->