<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Título do site -->
    <title><?php echo APP['name']; ?></title>
    
    <!-- Codificação caracteres e tamanho da página -->  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- SEO -->
    <meta name="description" content="<?php echo APP['desc']; ?>">
    <link rel="canonical" href="<?php echo APP['root']; ?>">
    <meta name="author" content="<?php echo APP['name']; ?>">
    <meta name="robots" content="index">

    <!-- google+ / Schema.org -->
    <meta itemprop="name" content="<?php echo APP['name']; ?>">
    <meta itemprop="description" content="<?php echo APP['desc']; ?>">
    <meta itemprop="image" content="#">

    <!-- Open Graph Facebook -->
    <meta property="og:title" content="<?php echo APP['name']; ?>">
    <meta property="og:description" content="<?php echo APP['desc']; ?>"/>
    <meta property="og:url" content="<?php echo SOCIAL['facebook_page']; ?>">
    <meta property="og:site_name" content="<?php echo APP['name']; ?>"/>
    <meta property="og:type" content="website">
    <meta property="og:image" content="#">

    <!-- Twitter -->
    <meta name="twitter:title" content="<?php echo APP['name']; ?>">
    <meta name="twitter:description" content="<?php echo APP['desc']; ?>">
    <meta name="twitter:url" content="<?php echo SOCIAL['twitter_site']; ?>">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:image" content="#">
    <meta name="twitter:creator" content="<?php echo SOCIAL['twitter_creator']; ?>">
    <!-- <meta name="twitter:site" content="@empresa"> -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Estilo customizado -->
    <link rel="stylesheet" type="text/css" href="css/style.css">

    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/merula_logo.png">

  </head>
  <body>
  <span class="endereco" data-endereco="<?=PAGSEGURO['url_site']?>"></span>

    <!-- header -->
    <header>
        <div class="container-fluid">
        <nav id="menu" class="navbar navbar-expand-md navbar-light fixed-top navbar-transparente">      
            <div class="container">
                <div class="row">
                    <div class="col">
                        <a href="/" class="navbar-brand">
                            <img id="logo-index" src="assets/merula_logo.png" height="70">
                        </a>
                    </div>
                    <div id="toggler" class="col text-right">
                        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#nav-principal">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                </div>        
                <div class="collapse navbar-collapse" id="nav-principal">
                    <ul id="lista-susp" class="navbar-nav text ml-auto">
                        <li class="nav-item">
                            <a href="/sobre" class="nav-link">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a href="/contato" class="nav-link">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a href="/clube-de-impacto" class="nav-link">Comprar</a>
                        </li>
                        <li class="nav-item">
                            <a href="/clube-de-impacto" class="btn btn-outline-light btn-assinar">Assinar</a>
                        </li>
                        <li class="nav-item" id="icon-social">
                            <a class="social-icon" href="<?php echo SOCIAL['instagram_page']; ?>" target="_blank"><i class="fab fa-instagram fa-lg"></i></a>
                            <a class="social-icon" href="<?php echo SOCIAL['facebook_page']; ?>" target="_blank"><i class="fab fa-facebook-f fa-lg"></i></a>
                            <a class="social-icon" href="<?php echo SOCIAL['whatsapp_api']; ?>" target="_blank"><i class="fab fa-whatsapp fa-lg"></i></a>
                        </li>
                    </ul>
                </div> 
            </div>
        </nav>
        </div>
    </header>
    <!-- end of header -->

    <?php $this->content() ?>

    <!-- dialogflow
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
    <df-messenger intent="WELCOME" chat-title="Equipe Merula" agent-id="8c65eb4c-27ab-4b37-98da-fb30aaa8a806" language-code="pt-br"></df-messenger>
    end of dialogflow -->

    <!-- Footer -->
    <footer id="footer">
        <div class="container">
            <div class="row" id="info-footer">
                <div class="col-md-4 text-left navbar-light nav-custom pt-5">
                    <div class="row">
                        <div class="col-6">
                            <ul class="navbar-nav ml-auto" id="nav-footer">
                                <li class="nav-item">
                                    <a href="/sobre" class="nav-link">Sobre</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/contato" class="nav-link">Contato</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/clube-de-impacto" class="nav-link">Assine</a>
                                </li>
                                <li class="nav-item">
                                    <a href="" class="nav-link">Compre</a>
                                </li>
                            </ul>    
                        </div>
                        <div class="col-6">
                            <ul class="navbar-nav ml-auto" id="nav-footer2">
                                <li class="nav-item">
                                    <a href="" class="nav-link">Política de privacidade</a>
                                </li>
                                <li class="nav-item">
                                    <a href="" class="nav-link">Pagamento e envio</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <img src="assets/merula_footer.svg" class="img-fluid" alt="">
                    <div class="row">
                      <div class="col-12">
                        <ul class="navbar-nav">
                            <li class="nav-item align-self-center" id="icon-social">
                                <a class="social-icon" href="<?php echo SOCIAL['instagram_page']; ?>" target="_blank"><i class="fab fa-instagram fa-lg"></i></a>
                                <a class="social-icon" href="<?php echo SOCIAL['facebook_page']; ?>" target="_blank"><i class="fab fa-facebook-f fa-lg"></i></a>
                                <a class="social-icon" href="<?php echo SOCIAL['whatsapp_api']; ?>" target="_blank"><i class="fab fa-whatsapp fa-lg"></i></a>
                            </li>
                        </ul>
                      </div>
                    </div>
                </div>
                <div id="dados-merula" class="col-md-4">
                  <div class="row">
                    <div class="row justify-content-end pt-5">
                      <div class="col">
                        <div>
                          <p>Merula Café Comércio de Produtos Alimentícios Ltda.</p>
                          <p>31.258.958/0001-00</p>
                        </div>
                        <div>
                          <p>R. Américo Rocha, 669, Marechal Hermes</p>
                          <p>Cep: 21555-300 - Rio de Janeiro - RJ</p>
                        </div>
                      </div>
                    </div>
                  </div> 
                </div>
            </div>
            <div class="row justify-content-center">
                <div id="form_news" class="col-12 align-items-center">
                  <form class="form-inline ml-4 text-center">
                      <label id="news" for="news"><h4>Receba nossa news letter</h4></label>
                      <input class="form-control mr-sm-2" type="email" placeholder="Digite seu e-mail" aria-label="Digite seu e-mail">
                      <button class="btn btn-outline-light btn-assinar" type="submit">Cadastrar</button>
                  </form> 
                </div>
            </div>
            <div id="copy" class="row">
                <div class="col-md-12 text-center pt-4 pb-4">
                    &copy; 2020 Merula Cafés Especiais de Impacto - Todos os direitos reservados.
                </div>
            </div>
        </div>
    </footer>
    <!-- end of Footer -->

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/cc010de742.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<?=PAGSEGURO['script']?>"></script>
    <script src="js/script.js"></script>
  </body>
</html>