<div id="carrinho">
<div class="espacos" id="espaco-clube-impacto">

</div>

<div class="container-fluid">
    <span class="endereco" data-endereco="<?php echo PAGSEGURO['url_site']; ?>"></span>
    <div id="titleCad" class="row mt-3 mb-3">
        <div class="col text-center">
            <h2 class="display-6">Detalhes do faturamento</h2>
        </div>
    </div>
    <form action="" id="formPagamento">  
        <div class="row mb-5">
            <div class="col-md-4">
                <div class="card shadow mb-4">
                    <div class="card-body">
                        <div id="titleCad" class="row mb-2">
                            <div class="col">
                                <!-- campo oculto para manipulacao interna -->
                                <!-- <input type="hidden" name="paymentMethod" id="paymentMethod" value="creditCard" checked> -->

                                <input type="hidden" name="receiverEmail" id="receiverEmail" value="<?php echo PAGSEGURO['email_loja']; ?>">

                                <input type="hidden" name="currency" id="currency" value="<?php echo PAGSEGURO['moeda']; ?>">

                                <!-- <input type="hidden" name="extraAmount" id="extraAmount" value=""> -->

                                <input type="hidden" name="notificationURL" id="notificationURL" value="<?php echo PAGSEGURO['url_notificacao']; ?>">

                                <input type="hidden" name="reference" id="reference" value="<?= $this->view->reference ?>">

                                <input type="hidden" name="noIntInstalQuantity" id="noIntInstalQuantity" value="2">

                                <input type="hidden" name="amountPerPayment" id="amountPerPayment" value="<?= $this->view->clube ?>">

                                <input type="hidden" name="codePlan" id="codePlan">
                                <h5 class="mb-4">Dados pessoais</h5>
                                <div class="row">
                                    <div class="col mb-3" id="div_form_input">
                                        <label for="senderName">Nome</label>
                                        <input class="form-control" type="text" name="senderName" id="senderName" placeholder="Nome completo" value="<?=isset($this->view->nome) ? $this->view->nome : '' ?>" required>
                                        <div class="invalid-feedback">
                                        Informe seu nome completo.
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 mb-3" id="div_form_input">
                                        <label for="creditCardHolderBirthDate">Data de Nascimento</label>
                                        <input class="form-control" type="text" name="creditCardHolderBirthDate" id="creditCardHolderBirthDate" placeholder="Data de Nascimento. Ex: 12/12/1912" value="<?=isset($this->view->dataNasc) ? $this->view->dataNasc : '' ?>" required>
                                    </div>
                                    <div class="col-md-6 mb-3" id="div_form_input">
                                        <label for="senderCPF">CPF</label>
                                        <input class="form-control" type="text" name="senderCPF" id="senderCPF" placeholder="CPF sem traço" value="<?=isset($this->view->cpf) ? $this->view->cpf : '' ?>" required>
                                    </div>    
                                </div>

                                <div class="col mb-3" id="div_form_input">
                                    <label for="senderEmail">E-mail</label>
                                    <input class="form-control" type="text" name="senderEmail" id="senderEmail" placeholder="Digite seu e-mail" value="<?=isset($this->view->email) ? $this->view->email : '' ?>" required>
                                    <div class="invalid-feedback">
                                    Informe seu e-mail.
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-3" id="div_form_input">
                                        <label for="senderAreaCode">DDD</label>
                                        <input class="form-control" type="text" name="senderAreaCode" id="senderAreaCode" placeholder="DDD" value="<?=isset($this->view->ddd) ? $this->view->ddd : '' ?>" required>
                                    </div>
                                    <div class="col" id="div_form_input">
                                        <label for="senderPhone">Telefone</label>
                                        <input class="form-control" type="text" name="senderPhone" id="senderPhone" placeholder="Somente número" value="<?=isset($this->view->phone) ? $this->view->phone : '' ?>" required>
                                    </div>    
                                </div>
                                <hr>

                                <h5 class="mt-4 mb-4">Endereço</h5>

                                <input type="hidden" name="shippingAddressRequired" id="shippingAddressRequired" value="true">

                                <div class="row">
                                    <div class="col-md-4" id="div_form_input">
                                        <label for="billingAddressPostalCode">CEP</label>
                                        <input class="form-control" type="text" name="billingAddressPostalCode" id="billingAddressPostalCode" placeholder="CEP sem traço" value="<?=isset($this->view->cep) ? $this->view->cep : '' ?>">
                                    </div>
                                    <div class="col-md-8 mb-3" id="div_form_input">
                                        <label for="billingAddressStreet">Logradouro</label>
                                        <input class="form-control" type="text" name="billingAddressStreet" id="billingAddressStreet" placeholder="Logradouro" value="<?=isset($this->view->addressStreet) ? $this->view->addressStreet : '' ?>" readonly>
                                        <div class="invalid-feedback">
                                        Informe o logradouro.
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-2 mb-3" id="div_form_input">
                                        <label for="billingAddressNumber">Número</label>
                                        <input class="form-control" type="text" name="billingAddressNumber" id="billingAddressNumber" placeholder="Número" value="<?=isset($this->view->number) ? $this->view->number : '' ?>">
                                    </div>
                                    <div class="col-md-5 mb-3" id="div_form_input">
                                        <label for="billingAddressComplement">Complemento</label>
                                        <input class="form-control" type="text" name="billingAddressComplement" id="billingAddressComplement" placeholder="Complemento" value="<?=isset($this->view->complement) ? $this->view->complement : '' ?>">
                                    </div>
                                    <div class="col-md-5 mb-3" id="div_form_input">
                                        <label for="billingAddressDistrict">Bairro</label>
                                        <input class="form-control" type="text" name="billingAddressDistrict" id="billingAddressDistrict" placeholder="Bairro" value="<?=isset($this->view->addressDistrict) ? $this->view->addressDistrict : '' ?>" readonly>
                                    </div>    
                                </div>
                                <div class="row">
                                    <div class="col-md-5 mb-3" id="div_form_input">
                                        <label for="billingAddressCity">Cidade</label>
                                        <input class="form-control" type="text" name="billingAddressCity" id="billingAddressCity" placeholder="Cidade" value="<?=isset($this->view->addressCity) ? $this->view->addressCity : '' ?>" readonly>
                                    </div>
                                    <div class="col-md-3 mb-3" id="div_form_input">
                                        <label for="billingAddressState">Estado</label>
                                        <input class="form-control" type="text" name="billingAddressState" id="billingAddressState" placeholder="UF" value="<?=isset($this->view->addressState) ? $this->view->addressState : '' ?>" readonly>
                                    </div>
                                    <div class="col-md-4 mb-3" id="div_form_input">
                                        <label for="billingAddressCountry">País</label>
                                        <input class="form-control" type="text" name="billingAddressCountry" id="billingAddressCountry" value="<?=isset($this->view->addressCountry) ? $this->view->addressCountry : '' ?>" readonly>
                                    </div>   
                                </div>

                                <hr>  

                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" name="shippingAdress" class="custom-control-input" id="shippingAdressOther" value="shippingAdressOther">
                                    <label class="custom-control-label" for="shippingAdressOther">Endereço de entrega diferente (selecione um meio de pagamento) </label><br>
                                </div>

                                <div class="row" id="formShippingAdressOption">
                                    <div class="row" class="creditCard">
                                        <div class="col-md-4 mb-3" id="div_form_input">
                                            <label for="shippingAddressPostalCode" class="creditCard">CEP</label>
                                            <input class="form-control" type="text" name="shippingAddressPostalCode" id="shippingAddressPostalCode" placeholder="CEP sem traço">
                                        </div>
                                        <div class="col-md-8 mb-3" id="div_form_input">
                                            <label for="shippingAddressStreet" class="creditCard">Logradouro</label>
                                            <input class="form-control" type="text" name="shippingAddressStreet" id="shippingAddressStreet" placeholder="Av. Rua" readonly>
                                            <div class="invalid-feedback">
                                            Informe o logradouro.
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row" class="creditCard">
                                        <div class="col-md-2 mb-3" id="div_form_input">
                                            <label for="shippingAddressNumber" class="creditCard">Número</label>
                                            <input class="form-control" type="text" name="shippingAddressNumber" id="shippingAddressNumber" placeholder="Número">
                                        </div>
                                        <div class="col-md-5 mb-3" id="div_form_input">
                                            <label for="shippingAddressComplement" class="creditCard">Complemento</label>
                                            <input class="form-control" type="text" name="shippingAddressComplement" id="shippingAddressComplement" placeholder="Complemento">
                                        </div>
                                        <div class="col-md-5 mb-3" id="div_form_input">
                                            <label for="shippingAddressDistrict" class="creditCard">Bairro</label>
                                            <input class="form-control" type="text" name="shippingAddressDistrict" id="shippingAddressDistrict" placeholder="Bairro" readonly>
                                        </div>    
                                    </div>

                                    <div class="row" class="creditCard">
                                        <div class="col-md-5 mb-3" id="div_form_input">
                                            <label for="shippingAddressCity" class="creditCard">Cidade</label>
                                            <input class="form-control" type="text" name="shippingAddressCity" id="shippingAddressCity" placeholder="Cidade" readonly>
                                        </div>
                                        <div class="col-md-3 mb-3" id="div_form_input">
                                            <label for="shippingAddressState" class="creditCard">Estado</label>
                                            <input class="form-control" type="text" name="shippingAddressState" id="shippingAddressState" placeholder="Sigla do Estado" readonly>
                                        </div>
                                        <div class="col-md-4 mb-3" id="div_form_input">
                                            <label for="shippingAddressCountry" class="creditCard">País</label>
                                            <input class="form-control" type="text" name="shippingAddressCountry" id="shippingAddressCountry" readonly>
                                        </div>   
                                    </div>
                                </div>
                            </div>  
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                
                <div class="card shadow mb-4">
                    <div class="card-body">
                        <div id="titleCad" class="row mb-2">
                            <div class="col">
                                <h5 class="mb-4">Pagamento</h5>
                                <div class="row mt-3 mb-3">
                                    <div class="col">
                                        <div class="row">
                                            <div class="custom-control custom-radio">
                                                <input type="radio" name="paymentMethod" class="custom-control-input" id="paymentMethod1" value="creditCard" onclick="tipoPagamento('creditCard')" required>
                                                <label class="custom-control-label" for="paymentMethod1">Cartão de crédito</label><br>
                                            </div>
                                        </div>
                                        <div class="row">    
                                            <div class="custom-control custom-radio">
                                                <input type="radio" name="paymentMethod" class="custom-control-input" id="paymentMethod2" value="boleto" onclick="tipoPagamento('boleto')" required>
                                                <label class="custom-control-label" for="paymentMethod2">Boleto</label>
                                            </div>
                                        </div>    
                                    </div>
                                </div>

                                <hr>  

                                <!-- <div class="row">
                                <p class="card-title">Frete</p>
                                </div>
                                <div class="row">
                                    
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Digite seu Cep" id="cepConsultaDados">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-dark cepConsulta" type="button" id="cepConsulta">Calcular frete</button>
                                        </div>
                                    </div>
                                    <div id="precoEprazo"></div>
                                    <span id="loading"></span>
                                    
                                </div> -->
                                <!-- <h5>Frete</h5>

                                <div class="custom-control custom-radio">
                                    <input type="radio" name="shippingType" id="pac" class="custom-control-input" value="1">
                                    <label class="custom-control-label" for="pac">PAC</label><br>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" name="shippingType" id="sedex" class="custom-control-input" value="2">
                                    <label class="custom-control-label" for="sedex">SEDEX</label><br>
                                </div>
                                <div class="custom-control custom-radio">
                                    <input type="radio" name="shippingType" id="semfrete" class="custom-control-input" value="3">
                                    <label class="custom-control-label" for="semfrete">Sem frete</label><br>
                                </div> -->
                                <div>
                                    <input type="hidden" name="shippingType" id="shippingType" value="">
                                    <input type="hidden" name="shippingCost" id="shippingCost" placeholder="Preço do frete. Ex: 2.10" class="form-control" value="<?=isset($this->view->freteCarrinho) ? $this->view->freteCarrinho : '' ?>">
                                </div>
                                <div class="row mb-3" id="formCreditCardOption">
                                    <div class="col">
                                        <div class="row mb-3">
                                            <label for="numCartao">Número do cartão</label>
                                            <div class="input-group">
                                                <input class="form-control" type="text" name="numCartao" id="numCartao" class="creditCard">
                                                <div class="input-group-append">
                                                    <span class="input-group-text bandeira-cartao"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <span id="loading"></span>
                                        <div class="row mb-3">
                                            <div class="col" id="div_form_input">
                                                <label for="mesValidade">Mês de Validade</label>
                                                <input class="form-control" type="text" name="mesValidade" id="mesValidade" maxlength="2" class="creditCard">
                                            </div>
                                            <div class="col" id="div_form_input">
                                                <label for="anoValidade">Ano de Validade</label>
                                                <input class="form-control" type="text" name="anoValidade" id="anoValidade" maxlength="4" class="creditCard">
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col-4" id="div_form_input">
                                                <label for="cvvCartao">CVV</label>
                                                <input class="form-control" type="text" name="cvvCartao" id="cvvCartao" maxlength="3" class="creditCard">
                                            </div>
                                            <div class="col-8" id="div_form_input">
                                                <label for="creditCardHolderCPF">CPF (Portador do cartão)</label>
                                                <input class="form-control" type="text" name="creditCardHolderCPF" id="creditCardHolderCPF" placeholder="CPF sem traço" class="creditCard" value="<?=isset($this->view->cpf) ? $this->view->cpf : '' ?>">
                                                <input class="form-control" type="hidden" name="bandeiraCartao" id="bandeiraCartao" class="creditCard">
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col" id="div_form_input">
                                                <label for="creditCardHolderName">Nome escrito no cartão</label>
                                                <input class="form-control" type="text" name="creditCardHolderName" id="creditCardHolderName" placeholder="Nome igual ao escrito no cartão" class="creditCard">
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col" id="div_form_input">
                                                <label for="qntParcelas">Nº de parcelas</label>
                                                <select class="custom-select d-block w-100" name="qntParcelas" id="qntParcelas" class="creditCard">
                                                    <option value="" class="creditCard">Selecione</option>
                                                </select>
                                            </div>
                                            <div class="col" id="div_form_input">
                                                <label for="valorParcelas">Valor Parcelas</label>
                                                <input class="form-control" type="text" name="valorParcelas" id="valorParcelas" class="creditCard">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <input type="hidden" name="tokenCartao" id="tokenCartao">
                                        </div>
                                        <hr>  
                                    </div>    
                                </div>   
                                <div class="row">
                                    <div class="col">    
                                        <div class="row">
                                            <input type="hidden" name="review" id="review" class="form-control" value="">
                                        </div>
                                        <div class="row" id="subtotal"></div>
                                        <div class="row" id="cart_message"></div>
                                        <div class="row">
                                            <input type="hidden" name="amount" id="amount" class="form-control">
                                            <input type="hidden" name="hashCartao" id="hashCartao">
                                        </div>
                                    </div>
                                </div>
                            </div>  
                        </div>
                    </div>
                </div>

                <?php if(@$this->view->listSubscribePayment != '') { ?>
                <div class="card shadow mb-4">
                    <div class="card-body">
                        <div class="row">
                            <h5>Detalhes do Clube de Impacto</h5>
                        </div>
                        <div class="row">
                            <p>Valor da assinatura mensal</p>
                        </div>
                        <div class="row">
                            <div class="col table-responsive">
                                <table class="table table-striped text-center">
                                    <thead>
                                        <tr>
                                            <td scope="col">Valor</td>
                                            <td scope="col">Frete</td>
                                            <td scope="col">Total</td>
                                        </tr>
                                    </thead>
                                    <tbody id="bodyTableSubscibe">
                                        <?=isset($this->view->listSubscribePayment) ? $this->view->listSubscribePayment : '' ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>    
            </div>
            <div class="col-md-4">
                <div class="card shadow">
                    <div class="card-body">
                        <div id="titleCad" class="row mb-2">
                            <div class="col">
                                <h5 class="mb-4">Resumo da Compra</h5>

                                <div class="row mb-3">
                                    <div class="col table-responsive">
                                        <table class="table table-striped text-center">
                                            <thead>
                                                <tr>
                                                    <td scope="col"><!-- <a class="social-icon-cart" href="/sair">Limpar carrinho</a> --></td>
                                                    <td scope="col">Descrição</td>
                                                    <td scope="col">Método</td>
                                                    <td scope="col">Quantidade</td>
                                                    <td scope="col">Valor</td>
                                                    <td scope="col">Total</td>
                                                    <td scope="col"></td>
                                                    <td scope="col"></td>
                                                </tr>
                                            </thead>
                                            <tbody id="bodyTable">
                                                <?=isset($this->view->listProducts) ? $this->view->listProducts : '' ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <hr>                                

                                <div class="row mb-3">
                                    <div class="col-6 align-self-center">
                                        <h5 class="card-title">Subtotal</h5>
                                    </div>
                                    <div class="col-6">
                                        <h5>R$ <span class="card-text" id="subtotalResumoCarrinho"><?=isset($this->view->subtotal) ? $this->view->subtotal : '' ?></span></h5>
                                    </div>
                                </div>
                                    
                                <!-- </div> -->
                                <hr> 

                                <div class="row mb-3">
                                    <div class="col-6 align-self-center">
                                        <h5 class="card-title">Frete</h5>
                                    </div>
                                    <div class="col-6">
                                        <h5>R$ <span class="card-text" data-frete="<?=isset($this->view->freteCarrinho) ? $this->view->freteCarrinho : '' ?>" id="freteCarrinho"><?=isset($this->view->freteCarrinho) ? $this->view->freteCarrinho : '' ?></span></h5>
                                    </div>
                                </div>
                                <!-- <div class="card-body"> -->

                                <hr>

                                <div class="row mb-3">
                                    <div class="col">
                                        <p class="card-title">Cupom de desconto</p>
                                        <div class="input-group mb-3">
                                            <input type="text" class="form-control" placeholder="Digite o cumpom">
                                            <div class="input-group-append">
                                                <button class="btn btn-outline-dark cepConsulta" type="button" id="button-addon2">Aplicar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <hr>

                                <!-- <div id="cardSubtotal" class="card-body">   -->
                                <div class="row mb-3">
                                    <div class="col-6 align-self-center">
                                        <h5 class="card-title">Total da Compra</h5>
                                    </div>
                                    <div class="col-6">    
                                        <h5 class="mb-3 mt-3">R$ <span id="totalResumoCarrinho" class="card-text" data-subtotal="<?=isset($this->view->subtotal) ? $this->view->subtotal : '' ?>" id="totalResumoCarrinho"><?=isset($this->view->subtotal) ? $this->view->subtotal : '' ?></span></h5>
                                    </div>
                                </div>  
                                
                                <hr>

                                <div class="row">
                                    <div class="col">
                                        <span class="mb-3" id="loading"></span>
                                        <span id="msg"></span>
                                        <button type="submit" id="btnFormPagamento" class="btn btn-lg btn-outline-dark btn-block cepConsulta">Finalizar Compra</button>
                                    </div>    
                                </div>
                            </div>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>      
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Olá, <?=@$this->view->primeiroNome?>. Podemos continuar?</h5>
      </div>
      <div class="modal-body">
        Se você quiser adicionar mais itens à sua cesta, ou queira mudar o frete, pode voltar ao carrinho. Se estiver tudo certo, podemos continuar com o pagamento.
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-md btn-outline-dark" href="/carrinho">Não, desejo alterar o carrinho</a>
        <button type="button" class="btn btn-md btn-outline-light cepConsulta" id="confirmCart">Sim, quero finalizar a compra</button>
      </div>
    </div>
  </div>
</div>

<!-- obrigado -->
<div class="modal fade" id="obrigadoPayment" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Tudo certo, <?=@$this->view->primeiroNome?>!</h5>
      </div>
      <div class="modal-body">
        <h3>Obrigado por comprar com a gente!</h3>
        <p>Te enviamos um e-mail com os dados da sua compra.</p>
        <p>Em caso de dúvida, entre em contato conosco.</p>
        <p id="paymentLink"></p>       
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-md btn-outline-light cepConsulta" href="/final-payment">Ok</a>
      </div>
    </div>
  </div>
</div>

<!-- nao aprovado -->
<div class="modal fade" id="naoAprovadoPayment" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Olá, <?=@$this->view->primeiroNome?>!</h5>
      </div>
      <div class="modal-body">
        <h3>Infelizmente sua compra não foi aprovada.</h3>
        <p>Entre em contato com a sua operadora de cartão de crédito.</p>
        <p>Em caso de dúvida, entre em contato conosco.</p>        
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-md btn-outline-light cepConsulta" href="/payment">Ok</a>
      </div>
    </div>
  </div>
</div>

<!-- erro -->
<div class="modal fade" id="erroPayment" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Olá, <?=@$this->view->primeiroNome?>!</h5>
      </div>
      <div class="modal-body">
        <h3>Erro. Não foi possível realizar o pagamento.</h3>
        <p>Verifique os dados informados na sua compra.</p>
        <p>Em caso de dúvida, entre em contato conosco.</p>        
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-md btn-outline-light cepConsulta" href="/payment">Ok</a>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="progress">
            <div class="progress-bar bg-warning progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                <span class="sr-only"></span>
            </div>
        </div>
    </div>
  </div>
</div>